<?xml version="1.0" encoding="utf-8"?><Database Name="DeviceInfo_Data" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sql2008;Initial Catalog=DeviceInfo_Data;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DeviceInfo_DataConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.deviceType" Member="deviceType">
    <Type Name="deviceType">
      <Column Name="deviceTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="deviceTypeName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>